version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: idea4rc_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: idea4rc_dm
      MYSQL_USER: idea4rc_llm
      MYSQL_PASSWORD: test@123
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d/

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: idea4rc_mysql_workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

  